# Generated by Django 5.0.9 on 2024-09-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0002_alter_aboutmodel_image_alter_newsmodel_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=264)),
                ('body', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='NewsModel',
            new_name='NewsUpdateModel',
        ),
    ]
