# Generated by Django 5.0.9 on 2024-09-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0003_faqmodel_rename_newsmodel_newsupdatemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupdatemodel',
            name='publish_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
