# Generated by Django 5.0.9 on 2024-10-01 16:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0004_newsupdatemodel_publish_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
